version: '3.5'

services:
  jenkins-docker:
    container_name: jenkins-docker
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - 'DOCKER_TLS_CERTDIR=/certs'
    volumes:
      - 'jenkins-docker-certs:/certs/client'
      - 'jenkins-data:/var/jenkins_home'
      - '$HOME:/home'
    ports:
      - '3000:3000'
    image: 'docker:19.03.8-dind'
  jenkins-ci:
    container_name: jenkins-ci
    build:
      context: .
      dockerfile: Jenkins.Dockerfile
    networks:
      - jenkins
    environment:
      - 'DOCKER_HOST=tcp://docker:2376'
      - 'DOCKER_CERT_PATH=/certs/client'
      - 'DOCKER_TLS_VERIFY=1'
    volumes:
      - 'jenkins-docker-certs:/certs/client'
      - 'jenkins-data:/var/jenkins_home'
      - '$HOME:/home'
    ports:
      - '8080:8080'
volumes:
  jenkins-docker-certs:
    name: jenkins-docker-certs
  jenkins-data:
    name: jenkins-data

networks:
  jenkins:
    name: jenkins
