pipeline {
    agent {
        docker {
            image 'node:12.16.1-alpine3.9'
            args '-p 3000:3000'
        }
    }
    environment {
      CI = 'true' 
    }
    stages {
        stage('Build') {
            steps {
                sh 'cd backend && npm install'
            }
        }
        stage('Test') {
            steps {
                sh 'cd backend && npm test'
            }
        }
    }
    post {
        always { 
            cleanWs()
        }
    }
}