pipeline {
    agent {
        dockerfile {
            dir 'backend'
            args '-p 3000:3000'
        }
    }
    environment {
      CI = 'true' 
    }
    stages {
        stage('Build') {
            steps {
                sh 'cd backend && npm install'
            }
        }
        stage('Test') {
            steps {
                sh 'cd backend && npm test'
            }
        }
    }
    post {
        success {
            withCredentials([string(credentialsId: 'githubToken', variable: 'TOKEN')]) {
                sh 'curl "https://api.GitHub.com/repos/klcantrell/home-search-dashboard/statuses/$GIT_COMMIT" \
                -H "Authorization: token $TOKEN" \
                -H "Content-Type: application/json" \
                -X POST \
                -d "{\\"state\\": \\"success\\",\\"context\\": \\"continuous-integration/jenkins\\", \\"description\\": \\"Build succeeded\\", \\"target_url\\": \\"http://ec2-18-220-234-212.us-east-2.compute.amazonaws.com:8080/job/home-search-dashboard_build/$BUILD_NUMBER/console\\"}"'
            }
        }
        failure {
            withCredentials([string(credentialsId: 'githubToken', variable: 'TOKEN')]) {
                sh 'curl "https://api.GitHub.com/repos/klcantrell/home-search-dashboard/statuses/$GIT_COMMIT" \
                -H "Authorization: token $TOKEN" \
                -H "Content-Type: application/json" \
                -X POST \
                -d "{\\"state\\": \\"failure\\",\\"context\\": \\"continuous-integration/jenkins\\", \\"description\\": \\"Build failed\\", \\"target_url\\": \\"http://ec2-18-220-234-212.us-east-2.compute.amazonaws.com:8080/job/home-search-dashboard_build/$BUILD_NUMBER/console\\"}"'
            }
        }
        always { 
            cleanWs()
        }
    }
}