pipeline {
    agent {
        docker {
            image 'node:12.16.1-alpine3.9'
            args '-p 3000:3000'
        }
    }
    environment {
      CI = 'true' 
    }
    stages {
        stage('Build') {
            steps {
                sh 'cd backend && npm install'
            }
        }
        stage('Test') {
            steps {
                sh 'cd backend && npm test'
            }
        }
    }
    post {
        success {
            githubNotify(
                status: 'SUCCESS', 
                context: 'continuous-integration/jenkins',
                repo: 'home-search-dashboard',
                account: 'klcantrell',
                sha: "$GIT_COMMIT",
                description: 'Build succeeded', 
                targetUrl: "http://ec2-18-220-234-212.us-east-2.compute.amazonaws.com:8080/job/home-search-dashboard_build/$BUILD_NUMBER/console",
                credentialsId: 'githubToken'
            )
        }
        failure {
            githubNotify(
                status: 'FAILURE', 
                context: 'continuous-integration/jenkins',
                repo: 'home-search-dashboard',
                account: 'klcantrell',
                sha: "$GIT_COMMIT",
                description: 'Build failed', 
                targetUrl: "http://ec2-18-220-234-212.us-east-2.compute.amazonaws.com:8080/job/home-search-dashboard_build/$BUILD_NUMBER/console",
                credentialsId: 'githubToken'
            )
        }
        always { 
            cleanWs()
        }
    }
}